#!/usr/bin/env bash

SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCES_DIR=${SETUP_DIR%/*}

# Install configs
for file in "$SETUP_DIR/configs/emacs"/*; do
    ln -s -f $file "$HOME/.config/emacs/"
done

# Install scripts
cat << %
# Add the folowing lines to your ~/.bash_profile:
export PATH="\$HOME/sources/setup/scripts:\$PATH"
%

# Install aur packages

declare -A AUR_URLS
AUR_URLS["emacs-pgtk-igc"]="https://aur.archlinux.org/emacs-pgtk-igc-git.git"

for file in "$SETUP_DIR/aur"/*; do
    name=$(basename $file)
    pkg_build_dir="$SOURCES_DIR/$name-aur"
    if [ ! -d $pkg_build_dir ]; then
        echo "$pkg_build_dir not found. Creating."
        mkdir -p $pkg_build_dir
        if [[ -v AUR_URLS[$name] ]]; then
            echo "Var $file exist. Cloning repo."
            git clone "${AUR_URLS[$name]}" $pkg_build_dir
        fi
    fi
    ln -s -f $file $pkg_build_dir/PKGBUILD
done
