#!/usr/bin/env bash

install_path=$HOME/software/zig
source_dir=$HOME/sources/zig
llvm_path=$LLVM
prev_path=`pwd`

echo "LLVM path: $llvm_path"
echo "zig source dir: $source_dir"
echo "zig installation dir: $install_path"

if [ ! -d $install_path ]; then
    echo "Installation path does not exist. Creating..."
    mkdir -p $install_path
fi

if [ -d $source_dir ]; then
    cd $source_dir
    git clean -dfx
    mkdir build
    cd build
    CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) cmake .. \
                              -DCMAKE_PREFIX_PATH=$llvm_path \
                              -DCMAKE_BUILD_TYPE=Release
    make -j$(nproc) install
    rm -rf $install_path/*
    cp -r stage3/* $install_path/
    cd $prev_path
fi
